services:
  relayer-api:
    build:
      context: ./packages/relayer-bundler
      dockerfile: Dockerfile
    ports:
      - "${RELAYER_PORT:-8080}:8080"
    restart: unless-stopped
    networks:
      - usp-network
    env_file:
      - ./packages/relayer-bundler/.env
    environment:
      - GIN_MODE=release

  usp-dapp:
    build:
      context: ./packages/dapp/usp-coin-interface
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    depends_on:
      - relayer-api
    restart: unless-stopped
    networks:
      - usp-network

networks:
  usp-network:
    driver: bridge