server {
    listen 80;
    
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        # Redireciona todas as requisições para o index.html (Essencial para o React Router)
        try_files $uri $uri/ /index.html;
    }
}